# Generated by Django 4.2.11 on 2024-04-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamacpp',
            name='chatLog',
            field=models.TextField(default=None, null=True),
        ),
    ]
